### ISSUE TITLE
Running in docker with https does not render root url to index.html

### ISSUE THREAD

**Issue by DallasP9124** [vercel/serve#707]
We created a dockerfile that builds the contents of our site and then runs `serve` with https enabled. When accessing `https://localhost:8443` a 404 is displayed.

run script
```sh
serve -l 8443 client/dist \
--config ./serve.json \  # to not render folder structure
--ssl-cert $SSL_CRT \
--ssl-key $SSL_KEY \
--ssl-pass ./k.pass
```

docker compose for startup
```yaml
services:
  site:
    image: private
    ports:
      - "8443:8443"
    volumes:
      - ./serve.json:/opt/app/serve.json
      - ./run.sh:/opt/app/run.sh
```

based on the simplicity of `serve` I don't really know where things have gone wrong.
